### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
user will can create an account that will store their saved data

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user can create an account and use an email/username and password to view saved information

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/139922991-c392a089-f290-428a-99fb-bee971ca7629.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a 'users' table
- [x] Update `data.sql` to create dummy users

### ☁️ Server

- [x] Update server/index.js to respond to a POST request
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to accept input for username/email
- [x] Create a component to accept input for a password

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
