### ISSUE TITLE
Feature: User can view their home page

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

After signing in, User can view their homepage

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view a homepage that shows useful graphs, charts, settings, and schedule

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/139924578-c42da17b-c982-47ad-8248-a0405e1fa2f8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a table that stores their schedule
- [x] Update `data.sql` to contain dummy data for user info

### ⚡ Client

- [x] Create a component to 
    - [x] show information
    - [x] update information
    - [x] greet the user

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
